### ISSUE TITLE
Unable to make it work...

### ISSUE THREAD

**Issue by Amir974** [pkozul/ha-floorplan-state-card#1]
Hi,

Looks like a great add on to HA.. but I was unable to make it work so far,
* I have a VERY basic SVG made using inkscape (only 2 shapes one ellipse and one rect) each associated with a different binary_sensor
* got the mqtt binary_sensor copied
* a group named floorplan & Last Motion sensor linked with the same binary_sensor's
* the customize settings (advanced version)with matching binary_sensor's as well

I end-up with a blank floorplan card on the tab I added it too - and no visual aspect..

How do I take it from here ?

**Comment by pkozul** [comment]
Assuming you're using Google Chrome, can you press F12 to open the Developer Tools. In the Console tab, you should see errors if there are any. Hit F5 to reload the page, and check for any errors there. Let me know how you go.

**Comment by Amir974** [comment]
saw my problem right away 🤦‍♂️ 
had the state-card-floorplan.html inside the floorplan directory and not above (custom_ui)
closing the issue :)

thanks!!!
